[project]
name = "fcb-attendance-tracker"
version = "0.1.0"
description = "FC Barcelona attendance tracker"
readme = "README.md"
authors = [{ name = "Roger Sole", email = "rogersolesotillo@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.28",
    "beautifulsoup4>=4.12",
    "python-dotenv>=1.0",
    "supabase>=2.31.0",
    "psycopg[binary]>=3.3.4",
]

[project.scripts]
fcb-attendance-tracker = "fcb_attendance-tracker:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
