[project]
name = "fcb-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Roger Sole", email = "rogersolesotillo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.28",
    "beautifulsoup4>=4.12",
    "python-dotenv>=1.0"
]

[project.scripts]
fcb-tracker = "fcb_tracker:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
