name: Fetch Barça Matches

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      # Setup the repository and install dependencies
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Install uv and Python
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          version: "0.12.3"
          python-version: "3.14"
          enable-cache: true
      - name: Sync project (install deps)
        run: |
          uv sync --dev
      # Run scripts to fetch matches and check requests
      - name: Run fetch and check scripts
        env:
          FOOTBALL_DATA_KEY: ${{ secrets.FOOTBALL_DATA_KEY }}
        run: |
          uv run python actions/fetch_matches.py
        # uv run python actions/check_requests.py
      # Commit changes and create a pull request if there are any updates
      - name: Generate branch variables
        id: vars
        run: |
          echo "branch=bot/update-matches-$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"
          echo "timestamp=$(date '+%Y-%m-%d %H:%M:%S')" >> "$GITHUB_OUTPUT"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.vars.outputs.branch }}
          base: main
          title: "Update matches"
          commit-message: "bot: Update matches.json"
          body: "Automatic update of `matches.json`. Github action run on ${{ steps.vars.outputs.timestamp }}."
      - name: Enable auto merge
        run: |
          gh pr merge \
            --squash \
            --delete-branch \
            "${{ steps.vars.outputs.branch }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}